# This file is generated by apps/cli/scripts/generate-homebrew-formula.js.
# Do not edit it manually.

class Onequery < Formula
  desc "CLI for querying and self-hosting OneQuery"
  homepage "https://github.com/wordbricks/onequery"
  license "Apache-2.0"
  version "0.1.45"

  on_macos do
    on_arm do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.45/onequery-npm-darwin-arm64-0.1.45.tgz"
      sha256 "9682a1d2bbdd41602c0c03f7f3c909cae5ba0caa3f749d5298d318093956883c"
    end

    on_intel do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.45/onequery-npm-darwin-x64-0.1.45.tgz"
      sha256 "027e8740c8775471d9b88aef080a292416afe192d25696929bfcf234a1bcd64d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.45/onequery-npm-linux-arm64-0.1.45.tgz"
      sha256 "d962bbe0095c7758e4a099647e991ade0f3997de8b5e59df20c0fdaf463e2eea"
    end

    on_intel do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.45/onequery-npm-linux-x64-0.1.45.tgz"
      sha256 "b3b5ef6df5a4d46a8a0fb68ac460f69f28f0bc09774318785aebc0a4f695b4fb"
    end
  end

  def install
    # COMMENT: Homebrew unpacks npm-style tarballs under the staged build
    # root, so package/vendor from the archive becomes vendor/ here.
    libexec.install "vendor"

    target_triple = if OS.mac?
      Hardware::CPU.arm? ? "aarch64-apple-darwin" : "x86_64-apple-darwin"
    elsif Hardware::CPU.arm?
      "aarch64-unknown-linux-musl"
    else
      "x86_64-unknown-linux-musl"
    end

    cli_binary = libexec/"vendor/#{target_triple}/onequery/onequery"

    # COMMENT: GitHub Actions artifact downloads normalize uploaded
    # CLI binaries to 0644, so Homebrew installs must restore the
    # executable bit before the wrapper launches them.
    chmod 0755, cli_binary

    (bin/"onequery").write_env_script(
      cli_binary,
      ONEQUERY_RUNTIME_ROOT: libexec/"vendor/#{target_triple}"
    )
  end

  test do
    assert_match "Usage: onequery config", shell_output("#{bin}/onequery config 2>&1")
  end
end
