# This file is generated by apps/cli/scripts/generate-homebrew-formula.js.
# Do not edit it manually.

class Onequery < Formula
  desc "CLI for querying and self-hosting OneQuery"
  homepage "https://github.com/wordbricks/onequery"
  license "Apache-2.0"
  version "0.1.20"

  on_macos do
    on_arm do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.20/onequery-npm-darwin-arm64.tgz"
      sha256 "40ebeeb2d90f519703fc4b79063f1b2981cf02e813a4ee1499f09a359fa0edd6"
    end

    on_intel do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.20/onequery-npm-darwin-x64.tgz"
      sha256 "23a84202e2b076e024443ab7a40023b3af079273271a132b6c9d5025da26d672"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.20/onequery-npm-linux-arm64.tgz"
      sha256 "7c324e5a1d927d1d90e8c72bc95c11e898be78270cd366f8acddbbde87941e7b"
    end

    on_intel do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.20/onequery-npm-linux-x64.tgz"
      sha256 "285928d3e1fb2977f29c0ae6c184a49ac37233102b6b93dc1eec8bac9f02769e"
    end
  end

  def install
    # COMMENT: Homebrew unpacks npm-style tarballs under the staged build
    # root, so package/vendor from the archive becomes vendor/ here.
    libexec.install "vendor"

    target_triple = if OS.mac?
      Hardware::CPU.arm? ? "aarch64-apple-darwin" : "x86_64-apple-darwin"
    elsif Hardware::CPU.arm?
      "aarch64-unknown-linux-musl"
    else
      "x86_64-unknown-linux-musl"
    end

    cli_binary = libexec/"vendor/#{target_triple}/onequery/onequery"

    # COMMENT: GitHub Actions artifact downloads normalize uploaded
    # CLI binaries to 0644, so Homebrew installs must restore the
    # executable bit before the wrapper launches them.
    chmod 0755, cli_binary

    (bin/"onequery").write_env_script(
      cli_binary,
      ONEQUERY_RUNTIME_ROOT: libexec/"vendor/#{target_triple}"
    )
  end

  test do
    assert_match "Usage: onequery config", shell_output("#{bin}/onequery config 2>&1")
  end
end
