# This file is generated by apps/cli/scripts/generate-homebrew-formula.js.
# Do not edit it manually.

class Onequery < Formula
  desc "CLI for querying and self-hosting OneQuery"
  homepage "https://github.com/wordbricks/onequery"
  license "Apache-2.0"
  version "0.1.51-alpha.1"

  on_macos do
    on_arm do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.51-alpha.1/onequery-npm-darwin-arm64-0.1.51-alpha.1.tgz"
      sha256 "a23a6d83b486cd04c6c36a05055bf7a72ebda02bb07ea58a4a9171b9e5dbe95e"
    end

    on_intel do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.51-alpha.1/onequery-npm-darwin-x64-0.1.51-alpha.1.tgz"
      sha256 "a41f77019be24d9c1094f3d5732048a17a4c4c9bb29d045717c5e0aa69ddd112"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.51-alpha.1/onequery-npm-linux-arm64-0.1.51-alpha.1.tgz"
      sha256 "a20613635155659ba3f391c0aba6f2ba7fcda27b7c797dc18f382d38ee857327"
    end

    on_intel do
      url "https://github.com/wordbricks/onequery/releases/download/cli-v0.1.51-alpha.1/onequery-npm-linux-x64-0.1.51-alpha.1.tgz"
      sha256 "6bf434cce27177eb162227df130a612df8545c810bbb154341e00fc66f07f5b6"
    end
  end

  def install
    # COMMENT: Homebrew unpacks npm-style tarballs under the staged build
    # root, so package/vendor from the archive becomes vendor/ here.
    libexec.install "vendor"

    target_triple = if OS.mac?
      Hardware::CPU.arm? ? "aarch64-apple-darwin" : "x86_64-apple-darwin"
    elsif Hardware::CPU.arm?
      "aarch64-unknown-linux-musl"
    else
      "x86_64-unknown-linux-musl"
    end

    cli_binary = libexec/"vendor/#{target_triple}/onequery/onequery"

    # COMMENT: GitHub Actions artifact downloads normalize uploaded
    # CLI binaries to 0644, so Homebrew installs must restore the
    # executable bit before the wrapper launches them.
    chmod 0755, cli_binary

    (bin/"onequery").write_env_script(
      cli_binary,
      ONEQUERY_RUNTIME_ROOT: libexec/"vendor/#{target_triple}"
    )
  end

  test do
    assert_match "Usage: onequery config", shell_output("#{bin}/onequery config 2>&1")
  end
end
